### ISSUE TITLE
Error Sniff-probes

### ISSUE THREAD

**Issue by AdelinoFB** [brannondorsey/sniff-probes#2]
Hello, im ussing a beaglebone black ,i have put an interface in monitor mode and the program has executed. i get the following error 
bash: ./sniff-probes.sh: Permission denied

Im ussing sudo

**Comment by brannondorsey** [comment]
It sounds like your `sniff-probes.sh` file doesn't have execute permissions. You can add them with:
```bash
chmod +x sniff-probes.sh
```

**Comment by AdelinoFB** [comment]
thanks brannondorsey, after that i get the following:
mon0 is the monitor interface
IFACE=mon0 ./sniff-probes.sh
awk: parse-tcpdump.awk: line 2: syntax error at or near ,
awk: parse-tcpdump.awk: line 7: syntax error at or near ,
awk: parse-tcpdump.awk: line 13: syntax error at or near ,
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on mon0, link-type IEEE802_11_RADIO (802.11 plus radiotap header), capture size 256 bytes
tcpdump: Unable to write output: Broken pipe

**Comment by brannondorsey** [comment]
Oh man, I remember coming across this ages ago. If I remember correctly, some OSes have distributions of `awk` that vary slightly. I've confirmed that this script works with `gawk`. Perhaps try downloading `gawk` and changing `awk` in `sniff-probes.sh` to `gawk`. 

I'm pretty sure that Ubuntu/debian ship with `gawk` as the default `awk` implementation. What OS are you on?

If that fixes your problem I'll update this repo to specifically use `gawk`.

**Comment by AdelinoFB** [comment]
My OS is debian ,i'll try this 
thanks

**Comment by brannondorsey** [comment]
I can confirm that my `awk` (and the `awk` on the Ubuntu machine that I developed this on) actually points to `gawk` :open_mouth:. Have `gawk` a go ;)

**Comment by AdelinoFB** [comment]
With gawk it works but how can i get origin  MAC?.Because the sniffer is showing sender MAC.Anyone could help me?

**Comment by AdelinoFB** [comment]
Thanks you Brannon ,now it goes!!
