### ISSUE TITLE
Update docs for gawk

### ISSUE THREAD

**Issue by brannondorsey** [brannondorsey/sniff-probes#3]
This `sniff-probes.sh` relies on `gawk`, not `awk`. Update documentation and add a line to check for the presence of `gawk` in `sniff-probes.sh`.

**Comment by AdelinoFB** [comment]
Hello, how can i use timeout in this script?

**Comment by brannondorsey** [comment]
Hi, can you tell me a little more about what you mean by "use timeout?"
